"""
exports/pdf_export.py - Unicode-safe PDF generation.

THE FIX: Helvetica (built-in PDF font) only supports Latin-1. LLM output
contains em-dashes, curly quotes, bullets etc. We sanitize via clean_text()
before every fpdf call so FPDFUnicodeEncodingException never fires.
"""

from fpdf import FPDF
from datetime import datetime

# ── Unicode -> ASCII map ──────────────────────────────────────────────────────
_UNICODE_MAP = {
    "\u2014": "--",   # em dash  (—)
    "\u2013": "-",    # en dash  (–)
    "\u2012": "-",    # figure dash
    "\u2010": "-",    # hyphen
    "\u2018": "'",    # left single quote  (\u2018)
    "\u2019": "'",    # right single quote (\u2019)
    "\u201c": '"',    # left double quote  (\u201c)
    "\u201d": '"',    # right double quote (\u201d)
    "\u2022": "*",    # bullet  (•)
    "\u2026": "...",  # ellipsis (…)
    "\u00a0": " ",    # non-breaking space
    "\u2192": "->",   # right arrow (→)
    "\u2212": "-",    # minus sign (−)
    "\u2713": "OK",   # check mark (✓)
    "\u2717": "X",    # cross (✗)
    "\u00a9": "(c)",  # copyright (©)
    "\u00ae": "(R)",  # registered (®)
    "\u2122": "(TM)", # trademark (™)
    "\u00b7": "*",    # middle dot (·)
}

def clean_text(text: str) -> str:
    """Replace Unicode chars with ASCII equivalents; strip any remaining non-latin-1."""
    for char, replacement in _UNICODE_MAP.items():
        text = text.replace(char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


# ── Colors ────────────────────────────────────────────────────────────────────
COLOR_SLATE     = (28,  28,  46)
COLOR_PARCHMENT = (245, 240, 232)
COLOR_ACCENT    = (44,  125, 50)
COLOR_MUTED     = (120, 120, 120)

TITLE      = "LegalEase -- Contract Analysis Report"
DISCLAIMER = (
    "DISCLAIMER: This document was generated by an AI assistant for informational "
    "purposes only. It does NOT constitute legal advice. Consult a licensed attorney "
    "before making any legal decisions."
)


class _LegalPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_draw_color(*COLOR_ACCENT)
            self.set_line_width(0.5)
            self.line(10, 12, 200, 12)
            self.set_y(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def generate_pdf(history: list, confidence=None) -> bytes:
    """Build a PDF brief from conversation history. Returns raw bytes."""
    pdf = _LegalPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*COLOR_SLATE)
    pdf.cell(0, 14, TITLE, ln=True)

    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(0, 7, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)

    if confidence is not None:
        try:
            from utils import risk_level
            level = risk_level(confidence)
        except Exception:
            level = "N/A"
        pdf.cell(0, 7, f"AI Confidence: {confidence:.0f}%  |  Risk Level: {level}", ln=True)

    pdf.set_draw_color(*COLOR_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y() + 3, 200, pdf.get_y() + 3)
    pdf.ln(6)

    # Disclaimer box
    pdf.set_fill_color(255, 243, 205)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 50, 0)
    pdf.multi_cell(0, 6, f"WARNING: {DISCLAIMER}", fill=True)
    pdf.ln(8)

    # Conversation turns
    for turn in history:
        role    = turn.get("role", "")
        content = clean_text(turn.get("content", ""))  # <-- THE FIX: sanitize before every call

        if role == "user":
            pdf.set_fill_color(*COLOR_PARCHMENT)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*COLOR_SLATE)
            pdf.cell(0, 8, "YOU", ln=True, fill=True)
            pdf.set_font("Helvetica", size=10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, content)
            pdf.ln(4)

        elif role == "assistant":
            pdf.set_fill_color(235, 245, 235)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*COLOR_ACCENT)
            pdf.cell(0, 8, "LEGALEASE AI", ln=True, fill=True)
            pdf.set_font("Helvetica", size=10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, content)
            pdf.ln(6)

    raw = pdf.output()
    if isinstance(raw, str):
        return raw.encode("latin-1")
    return bytes(raw)


def generate_markdown(history: list, confidence=None) -> str:
    """Convert conversation history to Markdown notes."""
    lines = []
    lines.append("# LegalEase -- Contract Analysis Notes")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    if confidence is not None:
        try:
            from utils import risk_level
            lines.append(f"*AI Confidence: {confidence:.0f}% | Risk Level: {risk_level(confidence)}*")
        except Exception:
            pass
    lines.append("")
    lines.append("> **Disclaimer:** For informational purposes only. Not legal advice.")
    lines.append("")
    lines.append("---")
    lines.append("")
    for i, turn in enumerate(history):
        role    = turn.get("role", "unknown")
        content = turn.get("content", "")
        lines.append(f"## {'You' if role == 'user' else 'LegalEase AI'} (Turn {(i // 2) + 1})")
        lines.append("")
        lines.append(content)
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)
